### ISSUE TITLE
Оформити титульну сторінку

### ISSUE THREAD

**Issue by RoksolanaHarasym** [MaryMak/INa-23#11]

**Comment by MaryMak** [comment]
Як має виглядати?

**Comment by julchep** [comment]
![m27b25d0](https://user-images.githubusercontent.com/38668477/39180356-588b0db4-47bf-11e8-9fda-71fc4a649bc0.gif)

**Comment by RoksolanaHarasym** [comment]
зайди на сайт кафедри світової
