### ISSUE TITLE
Написати план курсової роботи

### ISSUE THREAD

**Issue by MaryMak** [MaryMak/INa-23#5]
Вступ
1.Розділ 1
1.1 Підрозділ(інформація про автора)
1.2 Підрозділ(творчість)
2.Розділ 2(практична частина курсової роботи)
Висновки

**Comment by julchep** [comment]
на якому етапі курсової ви зараз?

**Comment by RoksolanaHarasym** [comment]
Я вже написала 2 розділи

**Comment by RoksolanaHarasym** [comment]
А ти ?#julchep

**Comment by julchep** [comment]
я дописую, дуже хочу закінчити, мені трохи не подобається мій план, хочу переписати
